### ISSUE TITLE
想问你一下你的翻译从什么时候开始的

### ISSUE THREAD

**Issue by fwqaaq** [xooch95/rust-atomics-and-locks-zh#1]
第一章中的翻译，和别人帮我 review 前后的：<https://github.com/fwqaaq/Rust_Atomics_and_Locks/pull/32/files#diff-2042a812b5d0b04a34e3a729e77b5bf711f88169790c6978bc7cb31ffc30d60eR397-R400>、<https://github.com/fwqaaq/Rust_Atomics_and_Locks/pull/30/files>

![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/db3da051-2ed2-45be-be11-c730f4255dee)
![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/3535ddb7-db3b-4da5-8185-52e6c38e337c)

![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/e5137ca2-476d-474e-b1e2-ea98bae92144)
![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/16d6ca6e-96f5-44a5-bbdb-3886af65d41d)

![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/5d1a28db-5f6f-4033-92ea-8201763f195b)
![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/7def9162-6b5a-4f85-88a9-69cce4856142)

![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/d51a55a8-6ea5-40eb-9253-cce803b6184e)
![image](https://github.com/fwqaaq/Rust_Atomics_and_Locks/assets/82551626/fa71da07-46ef-4c11-ad62-eb77d663ee54)

https://github.com/fwqaaq/Rust_Atomics_and_Locks

想问一下你从什么时候翻译的，有没有记录，感觉实在是太像（只是问一下）

**Comment by lattechen925** [comment]
5.2开始的

**Comment by fwqaaq** [comment]
> 5.2开始的

但是看了一下你的翻译，类似于“building block”、“allocation”...机翻严重，“分配”是动词 -> 文章里指的是“分配的内存”。

**Comment by lattechen925** [comment]
我的英文水平不太好，但是在我看来：
1、把作者想表达的逻辑，翻译通顺，读一遍或几遍能明白
2、 翻译的内容不曲解作者想表达的思想
3、 内容排版合理
等等。
对于细扣英文词性，必经水平有限。

**Comment by fwqaaq** [comment]
![image](https://github.com/xooch95/rust-atomics-and-locks-zh/assets/82551626/d559629f-d32d-40a2-ad80-7a5a3a3faa79)

你的翻译。。。
